EVENT_DIR = '/home/elijha/PycharmProjects/Cervix_Classification_GAN/Events/4_6'
TRAIN_IMG_DIR = '/home/elijha/Documents/Data/Cervix/train_converted'

BATCH_SIZE = 64

# Generator

GEN_CONV1_CHANNEL_NUM = 100
GEN_CONV2_CHANNEL_NUM = 100
GEN_CONV3_CHANNEL_NUM = 100
GEN_CONV4_CHANNEL_NUM = 100
GEN_CONV5_CHANNEL_NUM = 100
GEN_CONV6_CHANNEL_NUM = 100
GEN_CONV7_CHANNEL_NUM = 100

GEN_FILTER_SIZE = 4
